name: PulseItemsEntities
version: 1.0.17-a
main: com.pandapulsestudios.pulseitemsentities.PulseItemsEntities
depend: [PulseCore]
softdepend: [Citizens, ModelEngine, ItemsAdder, PulseCommands, PulseCore, PulseConfig]
api-version: 1.20
